# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PlcTfrtvCUu-IbM7byyP2LwBSaBhNMzb
"""

def sumar(a, b):
    return a+b

sumar (4, 5)

def es_par_o_impar(numero):
  if numero % 2 == 0:
      return "par"
  else:
      return "impar"

print(es_par_o_impar(6))

def saludar(nombre):
   return f"hola, {nombre}!"

print(saludar("Carlos"))

import math
def area_circulo(radio):
  return  math.pi * (radio ** 2)

print(area_circulo(2))

def tipo_numero(numero):
    if numero > 0:
        return "positivo"
    elif numero < 0:
        return "negativo"
    else:
        return "cero"

print(tipo_numero(-3))

def celcius_a_fahrenheit(celsius):
    return (celsius * 9/5) + 32

print(celcius_a_fahrenheit(30))

def cuadrado_de_un_numero(numero):
    return numero ** 2

print (cuadrado_de_un_numero(5))

def factorial_de_un_numero(numero):
    if numero == 0:
        return 1
    else:
        factorial = 1
        for i in range(1, numero + 1):
            factorial *= i
        return factorial

print (factorial_de_un_numero(6))

def vocales_en_una_palabra(palabra):
    vocales = "aeiouAEIOU"
    contador = 0
    for letra in palabra:
        if letra in vocales:
            contador += 1
    return contador

print (vocales_en_una_palabra("Hola Mundo"))

def tabla_de_multiplicar(numero):
    for i in range(1, 11):
        print(f"{numero} x {i} = {numero * i}")

print (tabla_de_multiplicar(5))

import math

def area_cuadrado():
    lado = float(input("Ingrese la longitud del lado del cuadrado: "))
    area = lado ** 2
    print("El área del cuadrado es:", area)

def area_triangulo():
    base = float(input("Ingrese la longitud de la base del triángulo: "))
    altura = float(input("Ingrese la longitud de la altura del triángulo: "))
    area = (base * altura) / 2
    print("El área del triángulo es:", area)

def area_circulo():
    radio = float(input("Ingrese la longitud del radio del círculo: "))
    area = math.pi * (radio ** 2)
    print("El área del círculo es:", area)

def menu():
    print("1. Calcular el área de un cuadrado")
    print("2. Calcular el área de un triángulo")
    print("3. Calcular el área de un círculo")
    print("4. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        area_cuadrado()
    elif opcion == "2":
        area_triangulo()
    elif opcion == "3":
        area_circulo()
    elif opcion == "4":
        print("¡opcion no valida!")

print(menu())